### ISSUE TITLE
TypeError: string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by Abogxlax** [v411e/ppim-migrator#11]
ppim-migrator version: 0.0.7

Having an issue where nothing will run due to the indices of the list being the wrong type. 

`Migrating favorites
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/localuser/.local/pipx/venvs/ppim-migrator/lib/python3.12/site-packages/ppim-migrator/__main__.py", line 24, in <module>
    cli()
  File "/home/localuser/.local/pipx/venvs/ppim-migrator/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/localuser/.local/pipx/venvs/ppim-migrator/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/localuser/.local/pipx/venvs/ppim-migrator/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/localuser/.local/pipx/venvs/ppim-migrator/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/localuser/.local/pipx/venvs/ppim-migrator/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/localuser/.local/pipx/venvs/ppim-migrator/lib/python3.12/site-packages/ppim-migrator/__main__.py", line 20, in migrate_favorites
    migrator.migrate_favorites()
  File "/home/localuser/.local/pipx/venvs/ppim-migrator/lib/python3.12/site-packages/ppim-migrator/migrator.py", line 40, in migrate_favorites
    photo_file_list = self.pp_api.get_photo_files_in_favorites()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/localuser/.local/pipx/venvs/ppim-migrator/lib/python3.12/site-packages/ppim-migrator/api/photoprism_api.py", line 73, in get_photo_files_in_favorites
    photos = self._filter_sidecar_files(photos)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/localuser/.local/pipx/venvs/ppim-migrator/lib/python3.12/site-packages/ppim-migrator/api/photoprism_api.py", line 64, in _filter_sidecar_files
    return [file for file in photo_files if not file["FileRoot"] == "sidecar"]
                                                ~~~~^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
`

**Comment by Abogxlax** [comment]
Never mind I messed up and used the wrong password. All's working well now.
